//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class nebula_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nebula_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.Resources.nebula.fr", typeof(nebula_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer avec ❤ par Unreal852.
        /// </summary>
        public static string AboutMadeBy {
            get {
                return ResourceManager.GetString("AboutMadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebula Version {0}.
        /// </summary>
        public static string AboutNebula {
            get {
                return ResourceManager.GetString("AboutNebula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci à Jetbrains pour fournir une licence Open Source gratuite..
        /// </summary>
        public static string AboutThanksTo {
            get {
                return ResourceManager.GetString("AboutThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter a la session d&apos;écoute.
        /// </summary>
        public static string AddToListeningSession {
            get {
                return ResourceManager.GetString("AddToListeningSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter a une playlist.
        /// </summary>
        public static string AddToPlaylist {
            get {
                return ResourceManager.GetString("AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparence.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artiste.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artistes.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par {0}.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher les mises à jour.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une Playlist.
        /// </summary>
        public static string CreatePlaylist {
            get {
                return ResourceManager.GetString("CreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la Playlist.
        /// </summary>
        public static string DeletePlaylist {
            get {
                return ResourceManager.GetString("DeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer la playlist &apos;{0}&apos;.
        /// </summary>
        public static string DeletePlaylistMsg {
            get {
                return ResourceManager.GetString("DeletePlaylistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer la Playlist.
        /// </summary>
        public static string EditPlaylist {
            get {
                return ResourceManager.GetString("EditPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter une Playlist.
        /// </summary>
        public static string ExportPlaylist {
            get {
                return ResourceManager.GetString("ExportPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une playlist.
        /// </summary>
        public static string FindPlaylist {
            get {
                return ResourceManager.GetString("FindPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Général.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer une Playlist.
        /// </summary>
        public static string ImportPlaylist {
            get {
                return ResourceManager.GetString("ImportPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clavier.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothèque.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu déjà existant.
        /// </summary>
        public static string MediaAlreadyExists {
            get {
                return ResourceManager.GetString("MediaAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette playlist contient déjà &apos;{0}&apos;, voulez-vous vraiment l’ajouter ?.
        /// </summary>
        public static string MediaAlreadyExistsMsg {
            get {
                return ResourceManager.GetString("MediaAlreadyExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muet.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lire.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Titre(s).
        /// </summary>
        public static string PlaylistTitles {
            get {
                return ResourceManager.GetString("PlaylistTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée de la playlist {0}.
        /// </summary>
        public static string PlaylistTotalDuration {
            get {
                return ResourceManager.GetString("PlaylistTotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentialité.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écoutés récemment.
        /// </summary>
        public static string RecentlyListened {
            get {
                return ResourceManager.GetString("RecentlyListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répéter.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume du son par défaut.
        /// </summary>
        public static string SettingsDefaultSoundLevel {
            get {
                return ResourceManager.GetString("SettingsDefaultSoundLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer le support des touches média du clavier.
        /// </summary>
        public static string SettingsKeyboardMediaEnable {
            get {
                return ResourceManager.GetString("SettingsKeyboardMediaEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur d&apos;augmentation / diminution du son via les touches média.
        /// </summary>
        public static string SettingsKeyboardMediaSoundIncDecValue {
            get {
                return ResourceManager.GetString("SettingsKeyboardMediaSoundIncDecValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aléatoire.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature.
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démute.
        /// </summary>
        public static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise a jour disponible.
        /// </summary>
        public static string UpdateCheckAvailable {
            get {
                return ResourceManager.GetString("UpdateCheckAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une mise à jour est disponible souhaitez-vous la télécharger ?.
        /// </summary>
        public static string UpdateCheckAvailableMsg {
            get {
                return ResourceManager.GetString("UpdateCheckAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de la vérification des mises à jour.
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de la recherche des mises à jour, veuillez réessayer plus tard. si ce problème persiste veuillez essayez de réinstaller Nebula..
        /// </summary>
        public static string UpdateCheckFailedMsg {
            get {
                return ResourceManager.GetString("UpdateCheckFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune mise à jour disponible.
        /// </summary>
        public static string UpdateCheckUpToDate {
            get {
                return ResourceManager.GetString("UpdateCheckUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune mise à jour disponible, voulez-vous forcer la mise a jour ?.
        /// </summary>
        public static string UpdateCheckUpToDateMsg {
            get {
                return ResourceManager.GetString("UpdateCheckUpToDateMsg", resourceCulture);
            }
        }
    }
}
